### ISSUE TITLE
No props Spawns

### ISSUE THREAD

**Issue by iceblader2013** [FaultyMatrix/qb-props#1]
Hey unfortunately I get no probs spawned.

this is my config and it is default qbcore.

Config = {}

Config.Props = {
    [1] = {     -- Delete this prop and replace it with what you like.
        model = "prop_printer_01",
        coords = vector4(228.97, -959.73, 29.36, 338.75),
    },
}

**Comment by ChickenDipper1** [comment]
Same, doesn't work

**Comment by FaultyMatrix** [comment]
Add PropSpawn() after line 21 in the script to fix this I believe

**Comment by FaultyMatrix** [comment]
I've also committed another permanent fix now for you.
